# TCL File Generated by Component Editor 25.1
# Wed Mar 25 20:17:59 CDT 2026
# DO NOT MODIFY


# 
# avalon_sdr "avalon_sdr" v1.0
#  2026.03.25.20:17:59
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module avalon_sdr
# 
set_module_property DESCRIPTION ""
set_module_property NAME avalon_sdr
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME avalon_sdr
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL sdram
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file sdram.sv SYSTEM_VERILOG PATH ip/sdram.sv TOP_LEVEL_FILE


# 
# parameters
# 


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clk clk Input 1


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset reset reset Input 1


# 
# connection point m0
# 
add_interface m0 avalon start
set_interface_property m0 addressUnits SYMBOLS
set_interface_property m0 associatedClock clock
set_interface_property m0 associatedReset reset
set_interface_property m0 bitsPerSymbol 8
set_interface_property m0 burstOnBurstBoundariesOnly false
set_interface_property m0 burstcountUnits WORDS
set_interface_property m0 doStreamReads false
set_interface_property m0 doStreamWrites false
set_interface_property m0 holdTime 0
set_interface_property m0 linewrapBursts false
set_interface_property m0 maximumPendingReadTransactions 0
set_interface_property m0 maximumPendingWriteTransactions 0
set_interface_property m0 readLatency 0
set_interface_property m0 readWaitTime 1
set_interface_property m0 setupTime 0
set_interface_property m0 timingUnits Cycles
set_interface_property m0 writeWaitTime 0
set_interface_property m0 ENABLED true
set_interface_property m0 EXPORT_OF ""
set_interface_property m0 PORT_NAME_MAP ""
set_interface_property m0 CMSIS_SVD_VARIABLES ""
set_interface_property m0 SVD_ADDRESS_GROUP ""

add_interface_port m0 avm_m0_read read Output 1
add_interface_port m0 avm_m0_write write Output 1
add_interface_port m0 avm_m0_writedata writedata Output 256
add_interface_port m0 avm_m0_address address Output 32
add_interface_port m0 avm_m0_readdata readdata Input 256
add_interface_port m0 avm_m0_readdatavalid readdatavalid Input 1
add_interface_port m0 avm_m0_byteenable byteenable Output 32
add_interface_port m0 avm_m0_waitrequest waitrequest Input 1
add_interface_port m0 avm_m0_burstcount burstcount Output 11


# 
# connection point req_addr
# 
add_interface req_addr conduit end
set_interface_property req_addr associatedClock clock
set_interface_property req_addr associatedReset ""
set_interface_property req_addr ENABLED true
set_interface_property req_addr EXPORT_OF ""
set_interface_property req_addr PORT_NAME_MAP ""
set_interface_property req_addr CMSIS_SVD_VARIABLES ""
set_interface_property req_addr SVD_ADDRESS_GROUP ""

add_interface_port req_addr req_addr export Input 32


# 
# connection point req_ready
# 
add_interface req_ready conduit end
set_interface_property req_ready associatedClock clock
set_interface_property req_ready associatedReset ""
set_interface_property req_ready ENABLED true
set_interface_property req_ready EXPORT_OF ""
set_interface_property req_ready PORT_NAME_MAP ""
set_interface_property req_ready CMSIS_SVD_VARIABLES ""
set_interface_property req_ready SVD_ADDRESS_GROUP ""

add_interface_port req_ready req_ready export Output 1


# 
# connection point req_rw
# 
add_interface req_rw conduit end
set_interface_property req_rw associatedClock clock
set_interface_property req_rw associatedReset ""
set_interface_property req_rw ENABLED true
set_interface_property req_rw EXPORT_OF ""
set_interface_property req_rw PORT_NAME_MAP ""
set_interface_property req_rw CMSIS_SVD_VARIABLES ""
set_interface_property req_rw SVD_ADDRESS_GROUP ""

add_interface_port req_rw req_rw export Input 1


# 
# connection point req_wdata
# 
add_interface req_wdata conduit end
set_interface_property req_wdata associatedClock clock
set_interface_property req_wdata associatedReset ""
set_interface_property req_wdata ENABLED true
set_interface_property req_wdata EXPORT_OF ""
set_interface_property req_wdata PORT_NAME_MAP ""
set_interface_property req_wdata CMSIS_SVD_VARIABLES ""
set_interface_property req_wdata SVD_ADDRESS_GROUP ""

add_interface_port req_wdata req_wdata export Input 512


# 
# connection point resp_rdata
# 
add_interface resp_rdata conduit end
set_interface_property resp_rdata associatedClock clock
set_interface_property resp_rdata associatedReset ""
set_interface_property resp_rdata ENABLED true
set_interface_property resp_rdata EXPORT_OF ""
set_interface_property resp_rdata PORT_NAME_MAP ""
set_interface_property resp_rdata CMSIS_SVD_VARIABLES ""
set_interface_property resp_rdata SVD_ADDRESS_GROUP ""

add_interface_port resp_rdata resp_rdata export Output 512


# 
# connection point resp_valid
# 
add_interface resp_valid conduit end
set_interface_property resp_valid associatedClock clock
set_interface_property resp_valid associatedReset ""
set_interface_property resp_valid ENABLED true
set_interface_property resp_valid EXPORT_OF ""
set_interface_property resp_valid PORT_NAME_MAP ""
set_interface_property resp_valid CMSIS_SVD_VARIABLES ""
set_interface_property resp_valid SVD_ADDRESS_GROUP ""

add_interface_port resp_valid resp_valid export Output 1


# 
# connection point req_valid
# 
add_interface req_valid conduit end
set_interface_property req_valid associatedClock clock
set_interface_property req_valid associatedReset ""
set_interface_property req_valid ENABLED true
set_interface_property req_valid EXPORT_OF ""
set_interface_property req_valid PORT_NAME_MAP ""
set_interface_property req_valid CMSIS_SVD_VARIABLES ""
set_interface_property req_valid SVD_ADDRESS_GROUP ""

add_interface_port req_valid req_valid export Bidir 1

